### ISSUE TITLE
Remove duplicate images folders

### ISSUE THREAD

**Issue by emilypstewart** [j4502/Local-Elections#14]
It looks like two "images" folders exist (upper and lowercase). 

<img width="849" alt="Screenshot of Repo & duplicate folders" src="https://cloud.githubusercontent.com/assets/774386/11054588/a695c458-8733-11e5-9a15-6cdb9deb6543.png">

**Easy fix:**
1. Move all the files from `Images` into `images`
2. Delete `Images` (uppercase) folder
3. Fix anything that references it in your HTML

**Comment by krohlwing** [comment]
Fixed this last night with Emily on office hours
