### ISSUE TITLE
Missing navigation and logo

### ISSUE THREAD

**Issue by emilypstewart** [j4502/Local-Elections#2]
Site is missing navigation and logo. Most likely, you'll need to implement something like:

```
<nav>
    <ul>
        <li>
            <a href="http://www.columbiamissourian.com/">
                <img src="assets/images/logo.png" alt="Elections Logo">
            </a>
        </li>

        <li>
            <a href="/">Menu</a>
        </li>
    </ul>
</nav>

```

**Comment by akbyler** [comment]
On the home page I have this for the nav: 

<ul>
    <li><a href="">Local</a></li>
    <li><a href="">State</a></li>
    <li><a href="">Voting Information</a></li>
    <li><a href="">Federal Elections</a></li>
  </ul>

Does that work or does it need to be wrapped in a <nav> tag?
