### ISSUE TITLE
Add ".html" to end of "individual-candidate" file

### ISSUE THREAD

**Issue by emilypstewart** [j4502/Local-Elections#9]
You'll need to add `.html` to the end of the [individual-candidate](https://github.com/j4502/Local-Elections/blob/Individual-candidate/individual-candidate) filename.

@laurenslome That's why you were seeing all white text in Atom instead of pretty colors ("syntax highlighting").

Better yet, you'll want to put this in it's own folder `individual-candidate` and place the file in that folder and rename it `index.html`

**Comment by krohlwing** [comment]
I think I fixed the file name
